//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Readable
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<long> Pages { get; set; }
        public string State { get; set; }
        public string Owned { get; set; }
        public byte[] FrontImage { get; set; }
        public string Cover { get; set; }
        public Nullable<System.Guid> AuthorId { get; set; }
    
        public virtual author author { get; set; }
    }
}
